### ISSUE TITLE
clarifications about implementation choices

### ISSUE THREAD

**Issue by zubcomandante** [Manacola/msbotframework-mongo-middlelayer#3]
Hi,
can you please help understanding some implementation choices you made in your project:
what is the reason behind using the same collection for user and session data, but with the 'userid' value formatted in two different ways, instead of using two different collections?
Is this choice tied to performance reasons? If yes, am I expected to create and index on 'userid'?

Thank you very much!

**Comment by aakashkag** [comment]
In my case when i read data , i need user data and some time user data with session data. It's  useless for me to query two time to get data.
