### ISSUE TITLE
how about put this on npm?

### ISSUE THREAD

**Issue by Wolke** [Manacola/msbotframework-mongo-middlelayer#4]
how about put this on npm?

**Comment by aakashkag** [comment]
Sure, I will do it soon.

**Comment by Wolke** [comment]
pls

**Comment by aakashkag** [comment]
Oops, sorry i didn't find time, Apology for this, This week i am put into npm. will ping here once it is done. Thanks.

https://www.linkedin.com/in/aakashkag/
aakashkaginfo@gmail.com

**Comment by Wolke** [comment]
come on,pls

**Comment by aakashkag** [comment]
@Wolke good news is, i am able to make into npm. will update repository and provide npm package details.

**Comment by Wolke** [comment]
orz, I make some change and already do this.
because ... I need it...
https://www.npmjs.com/package/botbuilder-mongodb-storage

**Comment by aakashkag** [comment]
I changed code and put into npm directory.

##NPM

https://www.npmjs.com/package/botbuilder-mongodb

npm install --save botbuilder-mongodb@3.1.1

You can find npm code into directory called npm_Code
