### ISSUE TITLE
MongoError: The dotted field 'BotBuilder.Data.PreferredLocale' in 'data.BotBuilder.Data.PreferredLocale' is not valid for storage.

### ISSUE THREAD

**Issue by alamusi** [Manacola/msbotframework-mongo-middlelayer#5]
Apparently, the BotBuilder.Data.PreferredLocale is stored as part of the userData, instead using a different rowKey like others, such as BotBuilder.Data.SessionState

The problem: when session.preferredLocale('zh-CN') is called, this invalid mongo field (BotBuilder.Data.PreferredLocale) is added under userdata.

The solution:
1. remove the rowKey condition check for 'userData' on line 32 and 56.
2. replace the '@' with '\uff0e' (utf16 dot symbol as mongo suggested) on line 33 and 57.

**Comment by aakashkag** [comment]
Thanks for report, Asap i Will look into it

**Comment by alamusi** [comment]
@aakashkag did you forget to commit in the changes?
