### ISSUE TITLE
Store all Conversations

### ISSUE THREAD

**Issue by abhishakskilrock** [Manacola/msbotframework-mongo-middlelayer#7]
Hi, Guys, I am able to store user conversation on MongoDB but it is storing last chat with the user only. Is there any method so that I can store all the conversations of the user in that database?

**Comment by cornopaez** [comment]
+1

**Comment by aakashkag** [comment]
@abhishakskilrock 
I am not sure I understood your requirement.
Do you want to store all incoming outgoing messages?
Ans: [https://github.com/Microsoft/BotBuilder/issues/2073](https://github.com/Microsoft/BotBuilder/issues/2073)

Or You want to append data in List
Ans : session.userData.users = [ ];
       session.userData.users = [ "a","b","c"]
